'''
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7
= 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''


def get_factors(n):
    return sum(2 for i in range(1, round(n ** 0.5 + 1)) if not n % i)


def get_triangular_number(num):
    return (num * (num + 1)) // 2


def get_five_hundred_factors():
    num = 1

    while True:
        triangular_number = get_triangular_number(num)
        factors = get_factors(triangular_number)

        if factors > 500:
            return triangular_number

        num += 1


if __name__ == '__main__':
    print(get_five_hundred_factors())
