'''
Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''


def solution_one():
    '''
    This solution is done without searching in google
    '''

    i = 1

    while True:
        tri = (i * (i + 1)) // 2

        # Pent and Hexa value is calculated using quadratic equation
        pent = (1 + (1 + 24 * tri) ** 0.5) % 6
        hexa = (1 + (1 + 8 * tri) ** 0.5) % 4

        if pent == hexa == 0 and tri > 40755:
            print(tri)
            break

        i += 1


def solution_two():
    '''
    This solution is done after searching in google
    '''

    i = 1

    while True:
        # Here, hexagonal numbers are the subset of triangle numbers
        # so, finding next number using hexagonal formula is enough for triangle number also.
        # And we need to check if the obtained hexagonal/triangle numbers is pentagonal number.

        hexagonal_numbers = i * (2 * i - 1)
        is_pentagonal_numbers = (1 + (1 + 24 * hexagonal_numbers) ** 0.5) % 6

        if is_pentagonal_numbers == 0 and hexagonal_numbers > 40755:
            print(hexagonal_numbers)
            break

        i += 1


solution_one()
solution_two()
