'''
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
'''


def Even_Fibonacci_numbers():
    first_num = 1
    second_num = 2

    while True:
        if first_num < 4000000:
            if first_num % 2 == 0:
                yield first_num

            third_num = first_num + second_num
            first_num = second_num
            second_num = third_num

        else:
            break


if __name__ == '__main__':
    print(sum(Even_Fibonacci_numbers()))
